#!/bin/sh
# Prints the funchess formula for its latest release, or nothing if there is none.
# funchess's release assets are bare executables, one per platform.
set -eu
. "$(dirname "$0")/../lib.sh"

REPO="anwarahmed/funchess"
tag=$(latest_tag "$REPO")
[ -n "$tag" ] || exit 0
version=${tag#v}
base="https://github.com/$REPO/releases/download/$tag"

sums=$(curl -fsSL "$base/SHA256SUMS")
mac_arm=$(sum_of "$sums" funchess-aarch64-apple-darwin)
mac_intel=$(sum_of "$sums" funchess-x86_64-apple-darwin)
linux_arm=$(sum_of "$sums" funchess-aarch64-unknown-linux-musl)
linux_intel=$(sum_of "$sums" funchess-x86_64-unknown-linux-musl)

cat <<FORMULA
# Generated by scripts/render.sh from the latest funchess release. Do not edit by
# hand; the next run overwrites it.
class Funchess < Formula
  desc "Chess for the terminal: solo, two players, or over the network"
  homepage "https://github.com/$REPO"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/funchess-aarch64-apple-darwin"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$base/funchess-x86_64-apple-darwin"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/funchess-aarch64-unknown-linux-musl"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/funchess-x86_64-unknown-linux-musl"
      sha256 "$linux_intel"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funchess-*"].first => "funchess"
    # funchess updates itself unless a package owns the copy. It looks for this marker at
    # ../share/funchess/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"funchess").mkpath
    (share/"funchess/managed-by").write "Homebrew; use brew upgrade funchess\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funchess --version")
  end
end
FORMULA
