#!/bin/sh
# Prints the funwordl formula for its latest release, or nothing if there is none.
# funwordl's release assets are bare executables, one per platform, as funwordl's are.
set -eu
. "$(dirname "$0")/../lib.sh"

REPO="anwarahmed/funwordl"
tag=$(latest_tag "$REPO")
[ -n "$tag" ] || exit 0
version=${tag#v}
base="https://github.com/$REPO/releases/download/$tag"

sums=$(curl -fsSL "$base/SHA256SUMS")
mac_arm=$(sum_of "$sums" funwordl-aarch64-apple-darwin)
mac_intel=$(sum_of "$sums" funwordl-x86_64-apple-darwin)
linux_arm=$(sum_of "$sums" funwordl-aarch64-unknown-linux-musl)
linux_intel=$(sum_of "$sums" funwordl-x86_64-unknown-linux-musl)

cat <<FORMULA
# Generated by scripts/render.sh from the latest funwordl release. Do not edit by
# hand; the next run overwrites it.
class Funwordl < Formula
  desc "Playful Wordle-style word game for the terminal, made for children"
  homepage "https://github.com/$REPO"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/funwordl-aarch64-apple-darwin"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$base/funwordl-x86_64-apple-darwin"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/funwordl-aarch64-unknown-linux-musl"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/funwordl-x86_64-unknown-linux-musl"
      sha256 "$linux_intel"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funwordl-*"].first => "funwordl"
    # funwordl updates itself unless a package owns the copy. It looks for this marker
    # at ../share/funwordl/managed-by from its binary; replacing a file Homebrew
    # installed would break the next brew upgrade.
    (share/"funwordl").mkpath
    (share/"funwordl/managed-by").write "Homebrew; use brew upgrade funwordl\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funwordl --version")
  end
end
FORMULA
