#!/bin/sh
# Prints the typeshelf formula for its latest release, or nothing if there is none.
# typeshelf's release assets are bare executables, one per platform.
set -eu
. "$(dirname "$0")/../lib.sh"

REPO="anwarahmed/typeshelf"
tag=$(latest_tag "$REPO")
[ -n "$tag" ] || exit 0
version=${tag#v}
base="https://github.com/$REPO/releases/download/$tag"

sums=$(curl -fsSL "$base/SHA256SUMS")
mac_arm=$(sum_of "$sums" typeshelf-aarch64-apple-darwin)
mac_intel=$(sum_of "$sums" typeshelf-x86_64-apple-darwin)
linux_arm=$(sum_of "$sums" typeshelf-aarch64-unknown-linux-musl)
linux_intel=$(sum_of "$sums" typeshelf-x86_64-unknown-linux-musl)

cat <<FORMULA
# Generated by scripts/render.sh from the latest typeshelf release. Do not edit by
# hand; the next run overwrites it.
class Typeshelf < Formula
  desc "Practice typing in the terminal by retyping classic books"
  homepage "https://github.com/$REPO"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/typeshelf-aarch64-apple-darwin"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$base/typeshelf-x86_64-apple-darwin"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/typeshelf-aarch64-unknown-linux-musl"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/typeshelf-x86_64-unknown-linux-musl"
      sha256 "$linux_intel"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["typeshelf-*"].first => "typeshelf"
    # typeshelf updates itself unless a package owns the copy. Since 0.2.5 it looks for
    # this marker at ../share/typeshelf/managed-by from its binary; replacing a file
    # Homebrew installed would break the next brew upgrade.
    (share/"typeshelf").mkpath
    (share/"typeshelf/managed-by").write "Homebrew; use brew upgrade typeshelf\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/typeshelf --version")
  end
end
FORMULA
