#!/bin/sh
# Prints the wordl formula for its latest release, or nothing if there is none.
# wordl's release assets are bare executables, one per platform (since 0.2.0; before
# that it was a bash script shipped as one archive).
set -eu
. "$(dirname "$0")/../lib.sh"

REPO="anwarahmed/wordl"
tag=$(latest_tag "$REPO")
[ -n "$tag" ] || exit 0
version=${tag#v}
base="https://github.com/$REPO/releases/download/$tag"

sums=$(curl -fsSL "$base/SHA256SUMS")
# A release from before 0.2.0 has no binaries at all: leave the formula as it is. One
# that has some but not all is broken, and sum_of fails loudly on it below.
printf '%s\n' "$sums" | grep -q ' \*\{0,1\}wordl-[a-z0-9_]*-' || exit 0
mac_arm=$(sum_of "$sums" wordl-aarch64-apple-darwin)
mac_intel=$(sum_of "$sums" wordl-x86_64-apple-darwin)
linux_arm=$(sum_of "$sums" wordl-aarch64-unknown-linux-musl)
linux_intel=$(sum_of "$sums" wordl-x86_64-unknown-linux-musl)

cat <<FORMULA
# Generated by scripts/render.sh from the latest wordl release. Do not edit by
# hand; the next run overwrites it.
class Wordl < Formula
  desc "Wordle-style word game for the terminal"
  homepage "https://github.com/$REPO"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/wordl-aarch64-apple-darwin"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$base/wordl-x86_64-apple-darwin"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/wordl-aarch64-unknown-linux-musl"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/wordl-x86_64-unknown-linux-musl"
      sha256 "$linux_intel"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["wordl-*"].first => "wordl"
    # wordl updates itself unless a package owns the copy. It looks for this marker at
    # ../share/wordl/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"wordl").mkpath
    (share/"wordl/managed-by").write "Homebrew; use brew upgrade wordl\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wordl --version")
  end
end
FORMULA
