#!/bin/sh
# Prints the wordl formula for its latest release, or nothing if there is none.
# wordl is a bash script: its release is one archive, the same on every platform.
set -eu
. "$(dirname "$0")/../lib.sh"

REPO="anwarahmed/wordl"
tag=$(latest_tag "$REPO")
[ -n "$tag" ] || exit 0
version=${tag#v}
base="https://github.com/$REPO/releases/download/$tag"

sums=$(curl -fsSL "$base/SHA256SUMS")
archive=$(sum_of "$sums" "wordl-$version.tar.gz")

cat <<FORMULA
# Generated by scripts/render.sh from the latest wordl release. Do not edit by
# hand; the next run overwrites it.
class Wordl < Formula
  desc "Wordle-style word game for the terminal"
  homepage "https://github.com/$REPO"
  url "$base/wordl-$version.tar.gz"
  sha256 "$archive"
  license "MIT"

  # macOS ships bash 3.2 and wordl needs 4.4 or newer.
  depends_on "bash"

  def install
    # The script looks for its word lists in words/ beside itself, after resolving
    # the link Homebrew puts in bin.
    libexec.install "wordl", "words"
    inreplace libexec/"wordl", "#!/usr/bin/env bash", "#!#{Formula["bash"].opt_bin}/bash"
    bin.install_symlink libexec/"wordl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wordl --version")
  end
end
FORMULA
