# Generated by scripts/render.sh from the latest funchess release. Do not edit by
# hand; the next run overwrites it.
class Funchess < Formula
  desc "Chess for the terminal: solo, two players, or over the network"
  homepage "https://github.com/anwarahmed/funchess"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.1/funchess-aarch64-apple-darwin"
      sha256 "a02e8aabbea226be9bee36e555fa3c35cf50207e618fa81ede1f7daaed83a38c"
    end
    on_intel do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.1/funchess-x86_64-apple-darwin"
      sha256 "71c7ffa1de559403f902e7185c1c614c3e2b41e525edb14e4b2f0418704a1661"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.1/funchess-aarch64-unknown-linux-musl"
      sha256 "5aec7162a867b0c37a18ddc675001faf66869466813829c1537f43d9be9cad00"
    end
    on_intel do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.1/funchess-x86_64-unknown-linux-musl"
      sha256 "68b76945bd26cea2c1ee531e46308246e4b10edbd46a9029114d7b7c59431486"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funchess-*"].first => "funchess"
    # funchess updates itself unless a package owns the copy. It looks for this marker at
    # ../share/funchess/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"funchess").mkpath
    (share/"funchess/managed-by").write "Homebrew; use brew upgrade funchess\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funchess --version")
  end
end
