# Generated by scripts/render.sh from the latest funchess release. Do not edit by
# hand; the next run overwrites it.
class Funchess < Formula
  desc "Chess for the terminal: solo, two players, or over the network"
  homepage "https://github.com/anwarahmed/funchess"
  version "0.2.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.5/funchess-aarch64-apple-darwin"
      sha256 "c6ed845b8a65558a125bf2b876c3e399f4e493751af3673c25256a702c6b9c7c"
    end
    on_intel do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.5/funchess-x86_64-apple-darwin"
      sha256 "cbe1e32000fe6550fb35e71b5cdcc0918f071dacbf58f47827315ff3d32dda6e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.5/funchess-aarch64-unknown-linux-musl"
      sha256 "3d61b7a67205d1c98bdaae196013cba18fa22925fc76d543355bc59ebb39354d"
    end
    on_intel do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.5/funchess-x86_64-unknown-linux-musl"
      sha256 "8ea02a5c03bfbe9c5942007332320d49dc3aca891da54931d59eb2e559ed9ece"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funchess-*"].first => "funchess"
    # funchess updates itself unless a package owns the copy. It looks for this marker at
    # ../share/funchess/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"funchess").mkpath
    (share/"funchess/managed-by").write "Homebrew; use brew upgrade funchess\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funchess --version")
  end
end
