# Generated by scripts/render.sh from the latest funchess release. Do not edit by
# hand; the next run overwrites it.
class Funchess < Formula
  desc "Chess for the terminal: solo, two players, or over the network"
  homepage "https://github.com/anwarahmed/funchess"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.3/funchess-aarch64-apple-darwin"
      sha256 "32810fe0b5e9fcc56184269e14e940451774ab2aa5267d8268476aaff3f534b2"
    end
    on_intel do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.3/funchess-x86_64-apple-darwin"
      sha256 "55b810957bfbd1527aadaf0fd3ef6ed388597403a723353f50d85f495b995b0a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.3/funchess-aarch64-unknown-linux-musl"
      sha256 "4b4c38466cad211c0248159e1922b3a439aebbcf688c796c73c2a008bb215c44"
    end
    on_intel do
      url "https://github.com/anwarahmed/funchess/releases/download/v0.2.3/funchess-x86_64-unknown-linux-musl"
      sha256 "e86d5da8d2cd578cda1d1db8b013c3a64ed1f633e483aaf38a357546bfc7aa14"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funchess-*"].first => "funchess"
    # funchess updates itself unless a package owns the copy. It looks for this marker at
    # ../share/funchess/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"funchess").mkpath
    (share/"funchess/managed-by").write "Homebrew; use brew upgrade funchess\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funchess --version")
  end
end
