# Generated by scripts/render.sh from the latest fungeo release. Do not edit by
# hand; the next run overwrites it.
class Fungeo < Formula
  desc "Geography quiz for children in the terminal: build a bridge, answer by answer"
  homepage "https://github.com/anwarahmed/fungeo"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.1/fungeo-aarch64-apple-darwin"
      sha256 "a441381207a21bcfeb9442a510cf16dd3ea217ef6b0f4ccfb47a0264373ff2a2"
    end
    on_intel do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.1/fungeo-x86_64-apple-darwin"
      sha256 "84635810ec6d398a0e28f92e528fcc8533a25fa91ea0117c32950199ca79a1ac"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.1/fungeo-aarch64-unknown-linux-musl"
      sha256 "5301bd8513ddf04ac8be8486e85d7c82c3ddbe54facd73dd0602103adab98ce9"
    end
    on_intel do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.1/fungeo-x86_64-unknown-linux-musl"
      sha256 "e50869bf2f50ff9ccdd00efcd0884a5098362788fb0d1d69fed7196bfaec51db"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["fungeo-*"].first => "fungeo"
    # fungeo updates itself unless a package owns the copy. It looks for this marker at
    # ../share/fungeo/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"fungeo").mkpath
    (share/"fungeo/managed-by").write "Homebrew; use brew upgrade fungeo\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fungeo --version")
  end
end
