# Generated by scripts/render.sh from the latest fungeo release. Do not edit by
# hand; the next run overwrites it.
class Fungeo < Formula
  desc "Geography quiz for children in the terminal: build a bridge, answer by answer"
  homepage "https://github.com/anwarahmed/fungeo"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.2/fungeo-aarch64-apple-darwin"
      sha256 "ae5a6a3ea7e3b45ae3417b7ad371c6588b896b991ecab649ab7c2a0af0926f27"
    end
    on_intel do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.2/fungeo-x86_64-apple-darwin"
      sha256 "0ba72135c7f33dcfe1b274bea061293ba56fc0dbc65b100c11821676b3340f04"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.2/fungeo-aarch64-unknown-linux-musl"
      sha256 "914f3b1ef2906c9273904430d2b61418ac2c7ad5d1a01fed637d08d042a04132"
    end
    on_intel do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.2/fungeo-x86_64-unknown-linux-musl"
      sha256 "50ccae638bb409b4374ccdf2124f5fcfbe328e04c8815e671e538ea51680d20e"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["fungeo-*"].first => "fungeo"
    # fungeo updates itself unless a package owns the copy. It looks for this marker at
    # ../share/fungeo/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"fungeo").mkpath
    (share/"fungeo/managed-by").write "Homebrew; use brew upgrade fungeo\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fungeo --version")
  end
end
