# Generated by scripts/render.sh from the latest fungeo release. Do not edit by
# hand; the next run overwrites it.
class Fungeo < Formula
  desc "Geography quiz for children in the terminal: build a bridge, answer by answer"
  homepage "https://github.com/anwarahmed/fungeo"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.0/fungeo-aarch64-apple-darwin"
      sha256 "046c07eb3b34a6672ec3758028b1b9e394eb2a7bc049465b827c1fddbf4eb0d2"
    end
    on_intel do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.0/fungeo-x86_64-apple-darwin"
      sha256 "b47d1ade27057b6002d7920f7eb68ad550e8f293c74bed67f1450829bbd6dc67"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.0/fungeo-aarch64-unknown-linux-musl"
      sha256 "ac371304e6c5590f3851618d9ca85bd2728bf3ec59e2eefdc2c8569257b66827"
    end
    on_intel do
      url "https://github.com/anwarahmed/fungeo/releases/download/v0.1.0/fungeo-x86_64-unknown-linux-musl"
      sha256 "8d68f7b9eaa9191c7ade962add61f9b64c406a0d7bdcac83b0847e6c6a27c407"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["fungeo-*"].first => "fungeo"
    # fungeo updates itself unless a package owns the copy. It looks for this marker at
    # ../share/fungeo/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"fungeo").mkpath
    (share/"fungeo/managed-by").write "Homebrew; use brew upgrade fungeo\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fungeo --version")
  end
end
