# Generated by scripts/render.sh from the latest funkitty release. Do not edit by
# hand; the next run overwrites it.
class Funkitty < Formula
  desc "Fun time with Pink Kitty: reading and typing games for young children"
  homepage "https://github.com/anwarahmed/funkitty"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.1/funkitty-aarch64-apple-darwin"
      sha256 "bf4bd3ac88131e4a1e5d887b63916f22590f93ad2526f82992236e9abb0b6172"
    end
    on_intel do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.1/funkitty-x86_64-apple-darwin"
      sha256 "d673a143df443d63624bc150b1de3ad5284260a8ca3991015e69c804f72ccb97"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.1/funkitty-aarch64-unknown-linux-musl"
      sha256 "a1ce2355a1531a68122ae63502e148fa02ec9b5734733a494f49f9be034cb32f"
    end
    on_intel do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.1/funkitty-x86_64-unknown-linux-musl"
      sha256 "49208482dc22208a6102cfb8e24aaef0e6f4ad0c43f23fb25c04745b92f4267a"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funkitty-*"].first => "funkitty"
    # funkitty updates itself unless a package owns the copy. It looks for this marker at
    # ../share/funkitty/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"funkitty").mkpath
    (share/"funkitty/managed-by").write "Homebrew; use brew upgrade funkitty\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funkitty --version")
  end
end
