# Generated by scripts/render.sh from the latest funkitty release. Do not edit by
# hand; the next run overwrites it.
class Funkitty < Formula
  desc "Fun time with Pink Kitty: reading and typing games for young children"
  homepage "https://github.com/anwarahmed/funkitty"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.0/funkitty-aarch64-apple-darwin"
      sha256 "f6480a76ceddd91d7f1e8a4b834b8d7c2ac59723e1f1716b7863121ee708d513"
    end
    on_intel do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.0/funkitty-x86_64-apple-darwin"
      sha256 "75599a1e346dcd839ffd3b1a9fe43a95a0995aeefa0b5ba40d5f472c8ff39481"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.0/funkitty-aarch64-unknown-linux-musl"
      sha256 "92a9515525efa5b4918db1045a867b5f04847b12316ce87560129973ddf2ded4"
    end
    on_intel do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.0/funkitty-x86_64-unknown-linux-musl"
      sha256 "3b98f4cc2af3a1af980dbd17c030ed28896dff4e8841423277db55f0230daee4"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funkitty-*"].first => "funkitty"
    # funkitty updates itself unless a package owns the copy. It looks for this marker at
    # ../share/funkitty/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"funkitty").mkpath
    (share/"funkitty/managed-by").write "Homebrew; use brew upgrade funkitty\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funkitty --version")
  end
end
