# Generated by scripts/render.sh from the latest funkitty release. Do not edit by
# hand; the next run overwrites it.
class Funkitty < Formula
  desc "Fun time with Pink Kitty: reading and typing games for young children"
  homepage "https://github.com/anwarahmed/funkitty"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.2/funkitty-aarch64-apple-darwin"
      sha256 "5001e5aa9f023a00925fe83b9e91735cbbb3bd77191bbc29ea3eea6fd4a840ea"
    end
    on_intel do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.2/funkitty-x86_64-apple-darwin"
      sha256 "27a280309d71062681d5968eb8e83658a7886744ee46a811e8ea00e1db6a3f90"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.2/funkitty-aarch64-unknown-linux-musl"
      sha256 "88a7b81922e0ab78c117c1fc50d3f030d820e67a63ceb065b55c36a913d25f67"
    end
    on_intel do
      url "https://github.com/anwarahmed/funkitty/releases/download/v0.1.2/funkitty-x86_64-unknown-linux-musl"
      sha256 "536ad729a09e9c35519bf190baf9c536bd6073e01f46b709cac5b012fb2af21e"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funkitty-*"].first => "funkitty"
    # funkitty updates itself unless a package owns the copy. It looks for this marker at
    # ../share/funkitty/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"funkitty").mkpath
    (share/"funkitty/managed-by").write "Homebrew; use brew upgrade funkitty\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funkitty --version")
  end
end
