# Generated by scripts/render.sh from the latest funwordl release. Do not edit by
# hand; the next run overwrites it.
class Funwordl < Formula
  desc "Playful Wordle-style word game for the terminal, made for children"
  homepage "https://github.com/anwarahmed/funwordl"
  version "0.1.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.1/funwordl-aarch64-apple-darwin"
      sha256 "2bd1199f040c909644756f2cfe31c73c3131172efa599ace6162cce409b13e27"
    end
    on_intel do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.1/funwordl-x86_64-apple-darwin"
      sha256 "9d286954cb220ac36a9be0903c0de110b9efe9216b3c8dd26bdb7d3af3b7339d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.1/funwordl-aarch64-unknown-linux-musl"
      sha256 "fd4eeb9d04a1adbb7b1025ff947d78ac9fad2464c2fe6978d07bd0bdc7ede74f"
    end
    on_intel do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.1/funwordl-x86_64-unknown-linux-musl"
      sha256 "f0ee6ec7afd38498874a023847a8262c3f0627a88693cd92913bab00aed768ff"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funwordl-*"].first => "funwordl"
    # funwordl updates itself unless a package owns the copy. It looks for this marker
    # at ../share/funwordl/managed-by from its binary; replacing a file Homebrew
    # installed would break the next brew upgrade.
    (share/"funwordl").mkpath
    (share/"funwordl/managed-by").write "Homebrew; use brew upgrade funwordl\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funwordl --version")
  end
end
