# Generated by scripts/render.sh from the latest funwordl release. Do not edit by
# hand; the next run overwrites it.
class Funwordl < Formula
  desc "Playful Wordle-style word game for the terminal, made for children"
  homepage "https://github.com/anwarahmed/funwordl"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.2/funwordl-aarch64-apple-darwin"
      sha256 "f2e74b81f7b68f1fe7a983c7784a75dc70ece55a43b2aabc0e5116f2545c9279"
    end
    on_intel do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.2/funwordl-x86_64-apple-darwin"
      sha256 "1ebf4f7b534ecf894ecefa1f9022b60d0d384fd5afc0fe7279ef86830566b8f4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.2/funwordl-aarch64-unknown-linux-musl"
      sha256 "32f88f6ad40e9e7284519e878fecd2044ffb6474155fa72ddce928c13f544867"
    end
    on_intel do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.2/funwordl-x86_64-unknown-linux-musl"
      sha256 "1482b52ee8ea93ee31fd8fdf9c3436de1b9d9820f141b33bb1733ba8182bea42"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funwordl-*"].first => "funwordl"
    # funwordl updates itself unless a package owns the copy. It looks for this marker
    # at ../share/funwordl/managed-by from its binary; replacing a file Homebrew
    # installed would break the next brew upgrade.
    (share/"funwordl").mkpath
    (share/"funwordl/managed-by").write "Homebrew; use brew upgrade funwordl\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funwordl --version")
  end
end
