# Generated by scripts/render.sh from the latest funwordl release. Do not edit by
# hand; the next run overwrites it.
class Funwordl < Formula
  desc "Playful Wordle-style word game for the terminal, made for children"
  homepage "https://github.com/anwarahmed/funwordl"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.0/funwordl-aarch64-apple-darwin"
      sha256 "5d84be64fcd2c526194cbe7adad4091af74d0451074f9b5a68bd8a77c71cca93"
    end
    on_intel do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.0/funwordl-x86_64-apple-darwin"
      sha256 "3ea124f365d0fad475b9d0d77930e556d19f0283beb17859121411d450151c80"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.0/funwordl-aarch64-unknown-linux-musl"
      sha256 "fe358d3ededc2345325c4731fe5152f0b04b99b478d5e55d8890f072aec5d3d2"
    end
    on_intel do
      url "https://github.com/anwarahmed/funwordl/releases/download/v0.1.0/funwordl-x86_64-unknown-linux-musl"
      sha256 "a5506cd28498720e0546f9dd71dd5c9503ae6a82de9cc3d26ab6f6a603f1e919"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["funwordl-*"].first => "funwordl"
    # funwordl updates itself unless a package owns the copy. It looks for this marker
    # at ../share/funwordl/managed-by from its binary; replacing a file Homebrew
    # installed would break the next brew upgrade.
    (share/"funwordl").mkpath
    (share/"funwordl/managed-by").write "Homebrew; use brew upgrade funwordl\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/funwordl --version")
  end
end
