# Generated by scripts/render.sh from the latest typeshelf release. Do not edit by
# hand; the next run overwrites it.
class Typeshelf < Formula
  desc "Practice typing in the terminal by retyping classic books"
  homepage "https://github.com/anwarahmed/typeshelf"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/typeshelf/releases/download/v0.2.3/typeshelf-aarch64-apple-darwin"
      sha256 "99232aecf805b95accf54d8905246cd1ca9af2576e55afde97f80ad4f83106ac"
    end
    on_intel do
      url "https://github.com/anwarahmed/typeshelf/releases/download/v0.2.3/typeshelf-x86_64-apple-darwin"
      sha256 "447bf6e47a5a00939d0ef5062c5189ee1b9bf79d1c04cd99596968b1708c01f9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/typeshelf/releases/download/v0.2.3/typeshelf-aarch64-unknown-linux-musl"
      sha256 "eb099cd16e4dfd4227c9155ff4b5d1348cc899c96d8a06390526119ffe9f9245"
    end
    on_intel do
      url "https://github.com/anwarahmed/typeshelf/releases/download/v0.2.3/typeshelf-x86_64-unknown-linux-musl"
      sha256 "198d840b97c973378e422921dca5894c799a4475e8e56d1fae384c7338cf7a29"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["typeshelf-*"].first => "typeshelf"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/typeshelf --version")
  end
end
