# Generated by scripts/render.sh from the latest typeshelf release. Do not edit by
# hand; the next run overwrites it.
class Typeshelf < Formula
  desc "Practice typing in the terminal by retyping classic books"
  homepage "https://github.com/anwarahmed/typeshelf"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/typeshelf/releases/download/v0.2.1/typeshelf-aarch64-apple-darwin"
      sha256 "0b2f17db63a2f660cd2b116931db169982339ddcc8f3d65f882406347da436c7"
    end
    on_intel do
      url "https://github.com/anwarahmed/typeshelf/releases/download/v0.2.1/typeshelf-x86_64-apple-darwin"
      sha256 "bfeb4e5066f42449ecf6d7511a6bf261486dd94daabba01658b9127b7d63d265"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/typeshelf/releases/download/v0.2.1/typeshelf-aarch64-unknown-linux-musl"
      sha256 "bfd6bdcc1e733586761ac466ae5809be124093b50497d3bf58fdad5cecb48e93"
    end
    on_intel do
      url "https://github.com/anwarahmed/typeshelf/releases/download/v0.2.1/typeshelf-x86_64-unknown-linux-musl"
      sha256 "6a026acab83671c437596e19b6a2e0d37a621ab40fce4bafdf9ce14afd3904dc"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["typeshelf-*"].first => "typeshelf"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/typeshelf --version")
  end
end
