# Generated by scripts/render.sh from the latest wordl release. Do not edit by
# hand; the next run overwrites it.
class Wordl < Formula
  desc "Wordle-style word game for the terminal"
  homepage "https://github.com/anwarahmed/wordl"
  url "https://github.com/anwarahmed/wordl/releases/download/v0.1.1/wordl-0.1.1.tar.gz"
  sha256 "c190f393f61b1dd1c30b9fd4efa04e71fbcc7c7869b945bda294758e44a93059"
  license "MIT"

  # macOS ships bash 3.2 and wordl needs 4.4 or newer.
  depends_on "bash"

  def install
    # The script looks for its word lists in words/ beside itself, after resolving
    # the link Homebrew puts in bin.
    libexec.install "wordl", "words"
    inreplace libexec/"wordl", "#!/usr/bin/env bash", "#!#{Formula["bash"].opt_bin}/bash"
    bin.install_symlink libexec/"wordl"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wordl --version")
  end
end
