# Generated by scripts/render.sh from the latest wordl release. Do not edit by
# hand; the next run overwrites it.
class Wordl < Formula
  desc "Wordle-style word game for the terminal"
  homepage "https://github.com/anwarahmed/wordl"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/wordl/releases/download/v0.2.1/wordl-aarch64-apple-darwin"
      sha256 "06b3569810bad27de3d88dad4b046275463af26c00812f622a29f90aab402e51"
    end
    on_intel do
      url "https://github.com/anwarahmed/wordl/releases/download/v0.2.1/wordl-x86_64-apple-darwin"
      sha256 "1472a036d6b5e290e6edc163916a1ff08541e17b803d58db8a2c2122cac13a99"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/wordl/releases/download/v0.2.1/wordl-aarch64-unknown-linux-musl"
      sha256 "0e49c4bd5f92e3658a9cde9311664ca864bdc0125cbb9129d12bcef1fcbd38a8"
    end
    on_intel do
      url "https://github.com/anwarahmed/wordl/releases/download/v0.2.1/wordl-x86_64-unknown-linux-musl"
      sha256 "ff33f3abdab3db186cd55b1b3855f05fa9d4f989447ffeceb2a4c5333192bded"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["wordl-*"].first => "wordl"
    # wordl updates itself unless a package owns the copy. It looks for this marker at
    # ../share/wordl/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"wordl").mkpath
    (share/"wordl/managed-by").write "Homebrew; use brew upgrade wordl\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wordl --version")
  end
end
