# Generated by scripts/render.sh from the latest wordl release. Do not edit by
# hand; the next run overwrites it.
class Wordl < Formula
  desc "Wordle-style word game for the terminal"
  homepage "https://github.com/anwarahmed/wordl"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/anwarahmed/wordl/releases/download/v0.2.3/wordl-aarch64-apple-darwin"
      sha256 "baca9d7fd16621667d9454282ff884006b9d590bd81113f08c2109a5cbaca992"
    end
    on_intel do
      url "https://github.com/anwarahmed/wordl/releases/download/v0.2.3/wordl-x86_64-apple-darwin"
      sha256 "cd7bcb043a00545fe8b489d98e26673cd3f8e95d225a63aae335012cabfa5a63"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/anwarahmed/wordl/releases/download/v0.2.3/wordl-aarch64-unknown-linux-musl"
      sha256 "69eac72c3d2f92539a0ad5f66d21d6478c5af6192bcda4fed43344cf66bda868"
    end
    on_intel do
      url "https://github.com/anwarahmed/wordl/releases/download/v0.2.3/wordl-x86_64-unknown-linux-musl"
      sha256 "0a6193e6b83e8852d010dbfb3036523ac816aa9daf973154e0ce46799ea24c16"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["wordl-*"].first => "wordl"
    # wordl updates itself unless a package owns the copy. It looks for this marker at
    # ../share/wordl/managed-by from its binary; replacing a file Homebrew installed
    # would break the next brew upgrade.
    (share/"wordl").mkpath
    (share/"wordl/managed-by").write "Homebrew; use brew upgrade wordl\n"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wordl --version")
  end
end
