#!/bin/sh
# Rewrites Formula/typeshelf.rb for the latest typeshelf release.
# Prints "unchanged", "no release" or the version it rendered.
set -eu

REPO="anwarahmed/typeshelf"
out="$(dirname "$0")/../Formula/typeshelf.rb"

# The latest release's page redirects to .../releases/tag/v<version>.
tag=$(curl -fsSLI -o /dev/null -w '%{url_effective}' "https://github.com/$REPO/releases/latest" | sed -n 's|.*/releases/tag/||p')
if [ -z "$tag" ]; then
    echo "no release"
    exit 0
fi
version=${tag#v}
base="https://github.com/$REPO/releases/download/$tag"

sums=$(curl -fsSL "$base/SHA256SUMS")
sum_of() {
    sum=$(printf '%s\n' "$sums" | awk -v f="typeshelf-$1" '$2 == f || $2 == "*" f { print $1 }')
    [ -n "$sum" ] || { echo "render.sh: release $tag has no checksum for typeshelf-$1" >&2; exit 1; }
    echo "$sum"
}
mac_arm=$(sum_of aarch64-apple-darwin)
mac_intel=$(sum_of x86_64-apple-darwin)
linux_arm=$(sum_of aarch64-unknown-linux-musl)
linux_intel=$(sum_of x86_64-unknown-linux-musl)

new=$(cat <<FORMULA
# Generated by scripts/render.sh from the latest typeshelf release. Do not edit by
# hand; the next run overwrites it.
class Typeshelf < Formula
  desc "Practice typing in the terminal by retyping classic books"
  homepage "https://github.com/$REPO"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/typeshelf-aarch64-apple-darwin"
      sha256 "$mac_arm"
    end
    on_intel do
      url "$base/typeshelf-x86_64-apple-darwin"
      sha256 "$mac_intel"
    end
  end

  on_linux do
    on_arm do
      url "$base/typeshelf-aarch64-unknown-linux-musl"
      sha256 "$linux_arm"
    end
    on_intel do
      url "$base/typeshelf-x86_64-unknown-linux-musl"
      sha256 "$linux_intel"
    end
  end

  def install
    # Each release asset is the bare executable, named for its platform.
    bin.install Dir["typeshelf-*"].first => "typeshelf"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/typeshelf --version")
  end
end
FORMULA
)

if [ -f "$out" ] && [ "$(cat "$out")" = "$new" ]; then
    echo "unchanged"
else
    printf '%s\n' "$new" > "$out"
    echo "$version"
fi
